#!/bin/bash
# Script generateChunks.sh: From the previous index files generated by the gztool, generates the byte ranges
#                           that will be used to retrieve the chunks of the gzip file

# COMMAND LINE INPUT
file=$1
block_lenght=$2
total_lines=$3
bucket=$4

# 1. GENERATE LINE INTERVAL LIST
intervals=$(awk -v block_len="$block_lenght" -v totlines="$total_lines" '
   BEGIN {
      end=""
      for( i = 1; i+block_len < totlines; i+=block_len )
         print paste i":"i+block_len;
         end=i
      print paste end":"totlines;
   }')

# 2. OBTAINING THE BYTE RANGES CORRESPONDING TO THE LINE INTERVALS
for intr in $intervals;
do
    # extract start and end line no.
    start=$(echo $intr | awk -F':' '{print $1}')
    end=$(echo $intr | awk -F':' '{print $2-1}')
    # get start and end block
    # find closest point with line no. lower than target line no.
    start_block=$(awk -v val="$start" '
        BEGIN{c=2; l=$c}
        {d=val-$c; if (d >= 0) {l=$c; bl=$1}}
        END{print bl}' "${file}i_tab.info")
    # find start of first block after desired chunk, to get last value of last block in chunk
    end_block=$(awk -v val="$end" '
        BEGIN{c=2; l=$c}
        {d=$c-val; if (d >= 0 && d_prev <=0) {l=$c; bl=$1-1}
        d_prev=d
        }
        END{print bl}' "${file}i_tab.info")
    echo "Start and end lines of the chunk:" $start $end "Start and end Bytes of the chunk:" $start_block $end_block
    echo $start" "$end" "$start_block" "$end_block >> "${file}.chunks.info"
done

# 3. UPLOADING USEFUL FILES TO THE BUCKET
lithops storage put "${file}.chunks.info" $bucket
