#!/bin/bash
# Script generateChunks.sh: From the previous index files generated by the gztool, generates the byte ranges
#                           that will be used to retrieve the chunks of the gzip file

# COMMAND LINE INPUT
file=$1
start=$2
end=$3
bucket=$4

rm "${file}.random_chunk_${start}_${end}.info"

# 1. OBTAINING THE BYTE RANGES CORRESPONDING TO THE LINE INTERVALS
    # get start and end block
    # find closest point with line no. lower than target line no.
    start_block=$(awk -v val="$start" '
        BEGIN{c=2; l=$c}
        {d=val-$c; if (d >= 0) {l=$c; bl=$1}}
        END{print bl}' "${file}i_tab.info")
    # find start of first block after desired chunk, to get last value of last block in chunk
    end_block=$(awk -v val="$end" '
        BEGIN{c=2; l=$c}
        {d=$c-val; if (d >= 0 && d_prev <=0) {l=$c; bl=$1-1}
        d_prev=d
        }
        END{print bl}' "${file}i_tab.info")
    echo "Start and end lines of the chunk:" $start $end "Start and end Bytes of the chunk:" $start_block $end_block
    echo $start" "$end" "$start_block" "$end_block > "${file}.random_chunk_${start}_${end}.info"

